#!/bin/bash
#
# build css
lessc ./dev/css/apg.less ./dev/css/apg.css
#
#build js
browserify ./src/apgweb.js > ./dev/js/apghtml.js
#
#build complete web page
f1=./dev/html/apgweb-top.html
f2=../apg-lib/apglib.css
f3=./dev/css/apg.css
f4=./dev/html/toAbout.html
f5=./dev/html/about.html
f6=./dev/html/toHelp.html
f7=./dev/html/help.html
f8=./dev/html/toBot.html
f9=./dev/js/apghtml.js
f0=./dev/html/apgweb-bot.html
cat $f1 $f2 $f3 $f4 $f5 $f6 $f7 $f8 $f9 $f0 > apg.html 
exit 0